#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-kimi"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "c598beabb1574a7e9a6e54ceef4abad2" }
]

[assets]
directory = "./public"
